version: '3.8'
services:
  json-server:
    image: clue/json-server
    ports:
      - "3001:80"
    volumes:
      - ${PWD}/mock/db.json:/data/db.json
    networks:
      - kraken-net 
  
networks:
  kraken-net:
    name: kraken-net
    driver: bridge